---
# tasks file for nginx
- name: install package
  apt:
    name: nginx
    state: present
    update-cache: yes

- name: service enabled
  service:
    name: nginx
    state: started
    enabled: yes

- name: Update nginx config files
  become: true
  template:
    src: templates/nginx.conf
    dest: "/etc/nginx/sites-available/default"
  notify: restart_nginx

- name: link nginx config
  become: true
  file:
    src: "/etc/nginx/sites-available/default"
    dest: "/etc/nginx/sites-enabled/default"
    state: link
  tags:
    - nginx
  notify: restart_nginx
